/**
 * The PATH-independent launcher (S30; §9 "Launcher"): `setup` copies
 * `dist/**` (which already carries `cost/prices.json` and `render/report.js`
 * via the S12b build rule) to `~/.showreceipts/bin/<version>/` and writes
 * `~/.showreceipts/bin/showreceipts-hook` — a POSIX `sh` script that prefers
 * a real global install (with `node_modules/.bin` and `/_npx/` PATH entries
 * filtered out and `npm_command=exec` treated as "not installed"), falls
 * back to the absolute node + copied `cli.js`, and answers `{}` when neither
 * resolves. win32 gets `showreceipts-hook.cmd` with the same logic; the
 * `.cmd` is written on every platform because Codex `commandWindows` and
 * Copilot `powershell` reference it.
 *
 * Alongside the scripts sits `launcher.json` (S02 `LauncherSidecar`, mode
 * 0600, atomic) — the only machine-readable record; nothing ever parses the
 * scripts themselves (S23c `inspect.ts` derives `resolvable` from the
 * sidecar).
 */
import fs from 'node:fs';
import { basename, delimiter, dirname, join, relative } from 'node:path';
import type { LauncherSidecar } from '../model/types.js';
import { atomicWriteFile, ensureDir, realpathOrSelf, statOrNull } from '../util/fs.js';
import { sha256 } from '../util/hash.js';
import { stableStringify } from '../util/json.js';

/** Every path the launcher install touches. */
export interface LauncherPaths {
  binDir: string;
  versionDir: string;
  launcher: string;
  launcherCmd: string;
  sidecar: string;
  cli: string;
}

/** The launcher file layout under `<showreceiptsHome>/bin`. */
export function launcherPaths(showreceiptsHome: string, version: string): LauncherPaths {
  const binDir = join(showreceiptsHome, 'bin');
  const versionDir = join(binDir, version);
  return {
    binDir,
    versionDir,
    launcher: join(binDir, 'showreceipts-hook'),
    launcherCmd: join(binDir, 'showreceipts-hook.cmd'),
    sidecar: join(binDir, 'launcher.json'),
    cli: join(versionDir, 'cli.js'),
  };
}

/** The node binary recorded at setup time: the PATH symlink and its realpath. */
export interface ResolvedNode {
  node: string;
  realpath: string;
}

/**
 * Resolves the node to embed (§9): walk PATH for an entry whose `<dir>/node`
 * resolves to the same realpath as `process.execPath`, preferring the
 * symlink (`/opt/homebrew/bin/node`) over the Cellar realpath so the
 * recorded path survives version bumps of the underlying install. Shim
 * directories (`node_modules/.bin`, `/_npx/`) are skipped. Falls back to
 * `execPath` itself.
 */
export function resolveNodePath(execPath: string, envPath: string | undefined): ResolvedNode {
  const real = realpathOrSelf(execPath);
  const base = basename(execPath);
  for (const dir of (envPath ?? '').split(delimiter)) {
    if (dir === '') continue;
    if (dir.endsWith('node_modules/.bin') || dir.includes('/_npx/') || dir.endsWith('node_modules\\.bin') || dir.includes('\\_npx\\')) continue;
    const candidate = join(dir, base);
    const stat = statOrNull(candidate);
    if (stat === null || !stat.isFile()) continue;
    if (realpathOrSelf(candidate) === real) return { node: candidate, realpath: real };
  }
  return { node: execPath, realpath: real };
}

/** Double-quotes a path for POSIX `sh`, escaping `\ $ ` "`. */
export function shQuote(p: string): string {
  return `"${p.replace(/([\\$`"])/g, '\\$1')}"`;
}

/** The POSIX launcher script (§9). Generated, never parsed; 0755. */
export function launcherScriptSh(node: string, nodeRealpath: string, cli: string): string {
  const qnode = shQuote(node);
  const qcli = shQuote(cli);
  return [
    '#!/bin/sh',
    '# showreceipts hook launcher — generated by `showreceipts setup`; safe to',
    '# delete (`setup` regenerates it). Never parsed by tooling: machine-readable',
    '# facts live in launcher.json beside this script.',
    `# node: ${node}`,
    `# node-realpath: ${nodeRealpath}`,
    `# cli: ${cli}`,
    'set -f',
    "CLEAN_PATH=''",
    'SAVED_IFS="$IFS"',
    "IFS=':'",
    'for dir in $PATH; do',
    '  case "$dir" in',
    '    */node_modules/.bin) continue ;;',
    '    */node_modules/.bin/) continue ;;',
    '    */_npx/*) continue ;;',
    '  esac',
    '  if [ -z "$CLEAN_PATH" ]; then',
    '    CLEAN_PATH="$dir"',
    '  else',
    '    CLEAN_PATH="$CLEAN_PATH:$dir"',
    '  fi',
    'done',
    'IFS="$SAVED_IFS"',
    'if [ "${npm_command:-}" != "exec" ]; then',
    '  if PATH="$CLEAN_PATH" command -v showreceipts >/dev/null 2>&1; then',
    '    PATH="$CLEAN_PATH" exec showreceipts "$@"',
    '  fi',
    'fi',
    `if [ -x ${qnode} ] && [ -f ${qcli} ]; then`,
    `  exec ${qnode} ${qcli} "$@"`,
    'fi',
    "printf '{}'",
    'exit 0',
    '',
  ].join('\n');
}

/** Doubles embedded `"` for a path inside cmd double quotes (cmd has no backslash escape). */
function cmdQuoteInner(p: string): string {
  return p.replace(/"/g, '""');
}

/** The win32 launcher (same logic, best-effort platform). CRLF line endings. */
export function launcherScriptCmd(node: string, cli: string): string {
  const qnode = cmdQuoteInner(node);
  const qcli = cmdQuoteInner(cli);
  return [
    '@echo off',
    'rem showreceipts hook launcher — generated by `showreceipts setup`; safe to delete.',
    'rem Prefers a real global install; npm exec shims are never trusted.',
    'if "%npm_command%"=="exec" goto local',
    'for /f "delims=" %%I in (\'where showreceipts.cmd 2^>nul ^| findstr /v /i "node_modules\\.bin" ^| findstr /v /i "_npx"\') do (',
    '  call "%%I" %*',
    '  exit /b %errorlevel%',
    ')',
    ':local',
    `if exist "${qnode}" if exist "${qcli}" (`,
    `  "${qnode}" "${qcli}" %*`,
    '  exit /b %errorlevel%',
    ')',
    'echo {}',
    'exit /b 0',
    '',
  ].join('\r\n');
}

/** Every file under `dir`, recursively, sorted for determinism. */
function walkFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => (a.name < b.name ? -1 : 1))) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkFiles(full));
    else if (entry.isFile()) out.push(full);
  }
  return out;
}

/** Writes `text` to `path` (mode applied) unless the content already matches. */
function writeIfChanged(path: string, text: string, mode: number): boolean {
  try {
    if (fs.readFileSync(path, 'utf8') === text) {
      fs.chmodSync(path, mode);
      return false;
    }
  } catch {
    // missing or unreadable — write it
  }
  atomicWriteFile(path, text, { mode });
  return true;
}

export interface InstallLauncherOptions {
  showreceiptsHome: string;
  /** The running install's `dist/` (`cli.js` must exist in it). */
  distDir: string;
  version: string;
  execPath: string;
  envPath: string | undefined;
  platform: string;
}

/** What `installLauncher` put in place. */
export interface InstalledLauncher extends LauncherPaths {
  node: string;
  nodeRealpath: string;
  /** Anything actually changed on disk (files copied or scripts rewritten). */
  changed: boolean;
  /** dist files copied this run (identical files are skipped by hash). */
  copied: number;
}

/**
 * Installs (or refreshes) the launcher: copies `dist/**` to
 * `bin/<version>/` (files identical by sha256 are skipped), writes both
 * scripts and the sidecar. Idempotent — a second run changes nothing.
 * Throws on a missing `dist/cli.js` or an unwritable home (the CLI shell
 * maps that to exit 1).
 */
export function installLauncher(opts: InstallLauncherOptions): InstalledLauncher {
  const paths = launcherPaths(opts.showreceiptsHome, opts.version);
  const distCli = join(opts.distDir, 'cli.js');
  if (statOrNull(distCli) === null) {
    throw new Error(`setup: cannot find the built CLI at ${distCli} — the launcher needs the package's dist/`);
  }
  ensureDir(opts.showreceiptsHome, 0o700);
  ensureDir(paths.binDir, 0o700);

  let copied = 0;
  for (const file of walkFiles(opts.distDir)) {
    const target = join(paths.versionDir, relative(opts.distDir, file));
    const data = fs.readFileSync(file);
    const existing = statOrNull(target);
    if (existing !== null && existing.size === data.length && sha256(fs.readFileSync(target)) === sha256(data)) continue;
    ensureDir(dirname(target), 0o700);
    atomicWriteFile(target, data, { mode: 0o600 });
    copied += 1;
  }

  const { node, realpath } = resolveNodePath(opts.execPath, opts.envPath);
  const shChanged = writeIfChanged(paths.launcher, launcherScriptSh(node, realpath, paths.cli), 0o755);
  const cmdChanged = writeIfChanged(paths.launcherCmd, launcherScriptCmd(node, paths.cli), 0o755);

  const sidecar: LauncherSidecar & { nodeRealpath: string } = {
    version: opts.version,
    node,
    cli: paths.cli,
    launcher: opts.platform === 'win32' ? paths.launcherCmd : paths.launcher,
    nodeRealpath: realpath,
  };
  const sidecarChanged = writeIfChanged(paths.sidecar, `${stableStringify(sidecar)}\n`, 0o600);

  return { ...paths, node, nodeRealpath: realpath, copied, changed: copied > 0 || shChanged || cmdChanged || sidecarChanged };
}
