/**
 * OpenCode writer (S30; §9 OpenCode row, roadmap): writes the plugin
 * template to `~/.config/opencode/plugins/showreceipts.ts` — a Bun plugin
 * forwarding `tool.execute.after` and `session.idle` to the launcher with
 * the event JSON on stdin. This file is one of the two template sites
 * allow-listed by `scripts/check-no-network.mjs` (S12b): process-spawning
 * words appear only inside the exported template string.
 */
import fs from 'node:fs';
import { dirname } from 'node:path';
import { atomicWriteFile } from '../../util/fs.js';
import { unifiedDiff } from '../diff.js';
import { makeResult, type WriterContext, type WriterOutcome } from '../plan.js';

/** The roadmap note attached to every OpenCode result. */
export const OPENCODE_ROADMAP_NOTE =
  'OpenCode support is on the roadmap: the plugin forwards tool.execute.after and session.idle to the launcher; receipts from these ledgers stay best-effort until OpenCode support lands.';

/** The plugin template (§9): Bun-spawned forwarding, JSON on stdin, fail-open. */
export function opencodePluginSource(launcherPath: string): string {
  return `/**
 * showreceipts OpenCode plugin — generated by \`showreceipts setup\` (roadmap
 * preview). Forwards tool results and session-idle events to the
 * showreceipts hook runtime with the event JSON on stdin. Fail-open: never
 * blocks the agent.
 */
const LAUNCHER = ${JSON.stringify(launcherPath)};

async function forward(event: string, payload: unknown): Promise<void> {
  try {
    const proc = Bun.spawn([LAUNCHER, "hook", "opencode", event], {
      stdin: "pipe",
      stdout: "ignore",
      stderr: "ignore",
    });
    proc.stdin.write(JSON.stringify(payload ?? {}));
    proc.stdin.end();
    await proc.exited;
  } catch {
    // fail-open: receipts never block the agent
  }
}

export const ShowreceiptsPlugin = async () => ({
  "tool.execute.after": async (input: unknown, output: unknown) =>
    forward("tool.execute.after", { input, output }),
  event: async ({ event }: { event: { type: string; properties?: unknown } }) => {
    if (event.type === "session.idle") await forward("session.idle", event.properties ?? {});
  },
});
`;
}

/** Writes/refreshes/removes the plugin file. */
export function apply(ctx: WriterContext): WriterOutcome {
  const path = ctx.target.path;
  const desired = opencodePluginSource(ctx.launcherPath);
  let text: string | null = null;
  try {
    text = fs.readFileSync(path, 'utf8');
  } catch {
    text = null;
  }

  try {
    if (ctx.remove) {
      if (text === null) return { result: makeResult(ctx, 'unchanged'), exit: 0 };
      const diff = unifiedDiff(text, '', path);
      let backup: string | null = null;
      if (!ctx.dryRun) {
        backup = ctx.backup(text);
        fs.unlinkSync(path);
      }
      return { result: makeResult(ctx, ctx.dryRun ? 'dry-run' : 'removed', { backup, diff }), exit: 0 };
    }
    if (text === desired) {
      return { result: makeResult(ctx, 'unchanged', { notes: [OPENCODE_ROADMAP_NOTE] }), exit: 0 };
    }
    const diff = unifiedDiff(text ?? '', desired, path);
    let backup: string | null = null;
    if (!ctx.dryRun) {
      fs.mkdirSync(dirname(path), { recursive: true });
      if (text !== null) backup = ctx.backup(text);
      atomicWriteFile(path, desired, text === null ? { mode: 0o600 } : {});
    }
    const action = ctx.dryRun ? 'dry-run' : text === null ? 'installed' : 'updated';
    return { result: makeResult(ctx, action, { backup, diff, notes: [OPENCODE_ROADMAP_NOTE] }), exit: 0 };
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    const message = `cannot write ${path} (${code ?? String(err)})`;
    return { result: makeResult(ctx, 'manual', { notes: [message] }), exit: 1, error: message };
  }
}
