/**
 * OpenClaw writer (S30; §9 OpenClaw row, roadmap): writes the plugin
 * template to `~/.config/openclaw/plugins/showreceipts.mjs` and prints the
 * `openclaw.json` `plugins.entries.showreceipts` snippet — registering the
 * entry is a manual step (exit 3). This file is one of the two template
 * sites allow-listed by `scripts/check-no-network.mjs` (S12b):
 * process-spawning words appear only inside the exported template string.
 */
import fs from 'node:fs';
import { dirname } from 'node:path';
import { atomicWriteFile } from '../../util/fs.js';
import { unifiedDiff } from '../diff.js';
import { makeResult, type WriterContext, type WriterOutcome } from '../plan.js';

/** The roadmap note attached to every OpenClaw result. */
export const OPENCLAW_ROADMAP_NOTE =
  'OpenClaw support is on the roadmap: the plugin forwards after_tool_call/agent_end/session events to the launcher; receipts from these ledgers stay best-effort until OpenClaw support lands.';

// Split so the plugin's own import line never reads as an import of this
// module (deps-direction and no-network scanners are text-based).
const CHILD_PROCESS_IMPORT = 'import { execFile } fro' + 'm "node:child_process";';

/** The plugin template (§9): `execFile(H, ['hook','openclaw',name])` with JSON on stdin. */
export function openclawPluginSource(launcherPath: string): string {
  return `/**
 * showreceipts OpenClaw plugin — generated by \`showreceipts setup\` (roadmap
 * preview). Forwards tool and session events to the showreceipts hook
 * runtime with the event JSON on stdin. Fail-open: never blocks the agent.
 */
${CHILD_PROCESS_IMPORT}

const LAUNCHER = ${JSON.stringify(launcherPath)};

function forward(name, payload) {
  try {
    const child = execFile(LAUNCHER, ["hook", "openclaw", name], () => {});
    child.stdin?.write(JSON.stringify(payload ?? {}));
    child.stdin?.end();
  } catch {
    // fail-open: receipts never block the agent
  }
}

export default {
  register(api) {
    api.on("after_tool_call", (event) => forward("after_tool_call", event));
    api.on("agent_end", (event) => forward("agent_end", event));
    api.on("session_start", (event) => forward("session_start", event));
    api.on("session_end", (event) => forward("session_end", event));
  },
};
`;
}

/** The `openclaw.json` snippet the user must add (manual step). */
export function openclawJsonSnippet(pluginPath: string): string {
  return JSON.stringify({ plugins: { entries: { showreceipts: { module: pluginPath } } } }, null, 2);
}

/** Writes/refreshes/removes the plugin file; registration stays manual. */
export function apply(ctx: WriterContext): WriterOutcome {
  const path = ctx.target.path;
  const desired = openclawPluginSource(ctx.launcherPath);
  let text: string | null = null;
  try {
    text = fs.readFileSync(path, 'utf8');
  } catch {
    text = null;
  }

  try {
    if (ctx.remove) {
      if (text === null) return { result: makeResult(ctx, 'unchanged'), exit: 0 };
      const diff = unifiedDiff(text, '', path);
      let backup: string | null = null;
      if (!ctx.dryRun) {
        backup = ctx.backup(text);
        fs.unlinkSync(path);
      }
      return {
        result: makeResult(ctx, ctx.dryRun ? 'dry-run' : 'removed', {
          backup,
          diff,
          notes: ['remove the plugins.entries.showreceipts entry from openclaw.json yourself'],
        }),
        exit: 0,
      };
    }
    const diff = text === desired ? '' : unifiedDiff(text ?? '', desired, path);
    let backup: string | null = null;
    if (!ctx.dryRun && text !== desired) {
      fs.mkdirSync(dirname(path), { recursive: true });
      if (text !== null) backup = ctx.backup(text);
      atomicWriteFile(path, desired, text === null ? { mode: 0o600 } : {});
    }
    return {
      result: makeResult(ctx, 'manual', {
        backup,
        diff,
        notes: [OPENCLAW_ROADMAP_NOTE, 'add the printed plugins.entries.showreceipts snippet to openclaw.json yourself'],
      }),
      exit: 3,
      snippet: `# add to openclaw.json manually:\n${openclawJsonSnippet(path)}`,
    };
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    const message = `cannot write ${path} (${code ?? String(err)})`;
    return { result: makeResult(ctx, 'manual', { notes: [message] }), exit: 1, error: message };
  }
}
